<?php $user = new App\Model\User(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MVC App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand">MVC App</a>
                <?php if ($user->isLoggedIn()): ?>
                <a href="<?php echo \Core\Url::get('auth/logout'); ?>">Logout</a>
                <?php endif; ?>
            </div>
        </nav>
    </header>
    <div class="container" style="padding-top: 20px">
        <?php require_once $content; ?>
    </div>
</body>
</html>